package ba.unsa.etf.rpr.Business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Confederation;
import ba.unsa.etf.rpr.exceptions.MyException;

import java.util.List;

/**
 * Business Logic Layer for management of Confederations
 *
 * @author Muhamed-droid
 */

public class ConfederationManager {

    public Confederation add(Confederation con) throws MyException {
        if (con.getId() != 0){
            throw new MyException("Can't add confederation with ID. ID is autogenerated");
        }


        try{
            return DaoFactory.confederationDao().add(con);
        }catch (MyException e){
            if (e.getMessage().contains("UQ_NAME")){
                throw new MyException("Confederation with same name exists");
            }
            throw e;
        }
    }

    public List<Confederation> getAll() throws MyException{
        return DaoFactory.confederationDao().getAll();
    }

}
